name: Build and Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang libc++-dev libc++abi-dev meson ninja-build \
            libboost-dev libglfw3-dev libspdlog-dev nlohmann-json3-dev libssl-dev \
            libgl1-mesa-dev xorg-dev

      - name: Setup Meson
        run: |
          pip install meson

      - name: Configure build
        run: |
          meson setup builddir --native-file=native-linux.ini --buildtype=release

      - name: Build
        run: |
          meson compile -C builddir

      - name: Package binary
        run: |
          mkdir -p release
          cp builddir/seraphbot release/
          cp README.md release/
          cp LICENSE release/
          tar -czf seraphbot-linux-x86_64.tar.gz -C release .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: seraphbot-linux
          path: seraphbot-linux-x86_64.tar.gz

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: seraphbot-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Future: Add Windows and macOS builds when ready
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     # Windows build steps with vcpkg or similar

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     # macOS build steps with homebrew
